background_opacity: 0.9

window:
  padding:
    x: 0
    y: 0
# Font configuration
font:
  size: 12.0
  # The normal (roman) font face to use.
  normal:
    family: JetBrainsMono Nerd Font
    # Style can be specified to pick a specific face.
    style: Normal

  # The bold font face
  bold:
    family: JetBrainsMono Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: JetBrainsMono Nerd Font
    # Style can be specified to pick a specific face.
    style: Italic
colors:
  # Default colors
  primary:
    background: '0x24283b'
    foreground: '0xa9b1d6'

  # Normal colors
  normal:
    black:   '0x32344a'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0x9699a8'

  # Bright colors
  bright:
    black:   '0x444b6a'
    red:     '0xff7a93'
    green:   '0xb9f27c'
    yellow:  '0xff9e64'
    blue:    '0x7da6ff'
    magenta: '0xbb9af7'
    cyan:    '0x0db9d7'
    white:   '0xacb0d0'
